create table tb_dna (id int8 generated by default as identity, dna_type int4, name TEXT, primary key (id));
create table tb_dna (id int8 generated by default as identity, dna_type int4, name TEXT, primary key (id));
create table tb_dna (id int8 generated by default as identity, dna_type int4, sequence TEXT, primary key (id));
create table tb_dna (id int8 generated by default as identity, dna_type int4, sequence TEXT, primary key (id));
