create table tb_category (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_dna (id int8 generated by default as identity, name TEXT, category_id int8, primary key (id));
alter table if exists tb_dna add constraint FKfjry6k9velk2cbqd64x6tq5wg foreign key (category_id) references tb_category;
INSERT INTO tb_category(name) VALUES('Human');
INSERT INTO tb_category(name) VALUES('Simios');
