apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-root-password
type: Opaque
stringData:
  password: root

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-username
type: Opaque
stringData:
  username: root

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-password
type: Opaque
stringData:
  password: root