apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-simioshuman-app-service
spec:
  selector:
    app: {{ .Release.Name }}-simioshuman-app
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  type: LoadBalancer